---
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: v1
kind: Secret
metadata:
  name: regsecret
  namespace: ${NAMESPACE}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: xsds==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: core2io
  namespace: ${NAMESPACE}
data:
  Vcore2io_VERSION: "v1.2.3"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: core2io
  labels:
    name: core2io
    app: core2io
    image: ${DOCKER_IMAGE_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: ${NUM_REPLICAS}
  template:
    metadata:
      labels:
        app: core2io
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
      - name: core2io
        image: "${DOCKER_IMAGE_NAME}:${docker_image_version}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
          name: api-port
        envFrom:
        - configMapRef:
            name: core2io
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: core2io
  name: core2io
  namespace: ${NAMESPACE}
spec:
  ports:
  - name: core2io
    port: 80
    targetPort: api-port
    protocol: TCP
  selector:
    app: core2io
---
